// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcXNtTrNgY1Q_PlEolhfoZThJqoswKyMA',
    appId: '1:7064578971:android:c974947ff1c4d6313e4f3e',
    messagingSenderId: '7064578971',
    projectId: 'trade-manager-29a9d',
    databaseURL: 'https://trade-manager-29a9d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trade-manager-29a9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD30IeW6fCDhTIYyVaFpjP0uRzlO8kyDLc',
    appId: '1:7064578971:ios:b34513a0cffefaf43e4f3e',
    messagingSenderId: '7064578971',
    projectId: 'trade-manager-29a9d',
    databaseURL: 'https://trade-manager-29a9d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trade-manager-29a9d.firebasestorage.app',
    iosBundleId: 'com.example.tradeManager',
  );
}
